
version: 1.0-{branch}-{build}

branches:
  only:
    - master 
    - appveyor

clone_folder : c:\projects\versa3d

image:
  - Visual Studio 2017

platform: x64

configuration: Release

matrix: 
  fast_finish: true

install:
  - set QTDIR=C:\Qt\5.10.0\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin

before_build:
  -cmd: |-
      mkdir build
      cd build
      cmake ..
build:
  project: c:\projects\versa3d\build\Versa3dVer2.sln


