
version: 1.0-{branch}-{build}

branches:
  only:
    - master 
    - appveyor

clone_folder : c:\projects\versa3d

image: Visual Studio 2017
platform : x64 

configuration: Release

matrix: 
  fast_finish: true

install:
  - set QTDIR=C:\Qt\5.10.0\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;

before_build:
  - cd c:\projects\versa3d
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE="%configuration%" ..

build_script:
  - cmake --build .  

after_build:
  - cd c:\projects\versa3d\build
  - 7z a c:\projects\versa3d\build\Versa3d.zip * -tzip

artifacts: 
  - path : c:\projects\versa3d\build\Versa3d.zip
    name : Versa3d.zip





