
version: 1.0-{branch}-{build}

branches:
  only:
    - master 
    - appveyor

clone_folder : c:\projects\versa3d

image:
  - Visual Studio 2017

configuration: Release

environment:
  matrix: 
    - platform: x64

matrix: 
  fast_finish: true

install:
  - set QTDIR=C:\Qt\5.10.0\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;

build_script:
  - cmd : "build.bat"


